line_length:
  warning: 150
  error: 180
disabled_rules:
  - identifier_name
  - force_cast
  - force_try
  - function_body_length
  - syntactic_sugar
  - shorthand_operator
included:
  - Yomu
  - YomuTests
excluded: # paths to ignore during linting. overridden by `included`.
  - Carthage
  - Pods
  - Yomu/R.generated.swift
